services:
  - type: web
    name: amr-anandha-nilayam-hostel
    runtime: static
    buildCommand: npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
